# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "go-langserver-unstable-${version}";
  version = "2017-06-24";
  rev = "66ff4f536c4fe4a5c525472820a563939a0ab00f";

  goPackagePath = "github.com/sourcegraph/go-langserver";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/sourcegraph/go-langserver";
    sha256 = "01cmxw6pka6i7c9kabn0bsap0i9700j262p5rclz3ipr889gbqxa";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
