# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/beorn7/perks";
    fetch = {
      type = "git";
      url = "https://github.com/beorn7/perks";
      rev = "4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9";
      sha256 = "1hrybsql68xw57brzj805xx2mghydpdiysv3gbhr7f5wlxj2514y";
    };
  }
  {
    goPackagePath = "github.com/gogo/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/gogo/protobuf";
      rev = "dda3e8acadcc9affc16faf33fbb229db78399245";
      sha256 = "1f1lm6bgwnrd985n1aagqw0bxfx37z71fwfcijiz9k258vj4wlga";
    };
  }
  {
    goPackagePath = "github.com/golang/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/golang/protobuf";
      rev = "6a1fa9404c0aebf36c879bc50152edcc953910d2";
      sha256 = "0dsd6vlfdyarn3v822x9p2s94gfi5lhvqc2vm3bqmqjgcik3c51z";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/golang-lru";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/golang-lru";
      rev = "0a025b7e63adc15a622f29b0b2c4c3848243bbf6";
      sha256 = "1iq7lbpsz7ks052mpznmkf8s4k43p51z4dik2n9ivrxk666q2wxi";
    };
  }
  {
    goPackagePath = "github.com/matttproud/golang_protobuf_extensions";
    fetch = {
      type = "git";
      url = "https://github.com/matttproud/golang_protobuf_extensions";
      rev = "c12348ce28de40eed0136aa2b644d0ee0650e56c";
      sha256 = "1d0c1isd2lk9pnfq2nk0aih356j30k3h1gi2w0ixsivi5csl7jya";
    };
  }
  {
    goPackagePath = "github.com/neelance/parallel";
    fetch = {
      type = "git";
      url = "https://github.com/neelance/parallel";
      rev = "4de9ce63d14c18517a79efe69e10e99d32c850c3";
      sha256 = "1favqfs36nlyfv72icl4mfcd4qd65w0aljhvhjryzzkv2g5hgn3l";
    };
  }
  {
    goPackagePath = "github.com/opentracing/basictracer-go";
    fetch = {
      type = "git";
      url = "https://github.com/opentracing/basictracer-go";
      rev = "1b32af207119a14b1b231d451df3ed04a72efebf";
      sha256 = "0hs969asib4yqj5k755zr0byz2iqvjbs6z1szcnr50q6fihigca0";
    };
  }
  {
    goPackagePath = "github.com/opentracing/opentracing-go";
    fetch = {
      type = "git";
      url = "https://github.com/opentracing/opentracing-go";
      rev = "aaf6cd9717693889e097bc6df95358a0600a34f1";
      sha256 = "0i8qwkmap3k2kczjgsl8x6hc1d56gcgp1nz30b5j55hzkpq53v9l";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_golang";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_golang";
      rev = "26b897001974f2b4ee6688377873e4d6f61d533c";
      sha256 = "0f7mp67gqlb103ryabdsscsdzf64frhnbwx0xrk7skw7qds0axx1";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_model";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_model";
      rev = "6f3806018612930941127f2a7c6c453ba2c527d2";
      sha256 = "1413ibprinxhni51p0755dp57r9wvbw7xgj9nmdaxmhzlqhc86j4";
    };
  }
  {
    goPackagePath = "github.com/prometheus/common";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/common";
      rev = "3e6a7635bac6573d43f49f97b47eb9bda195dba8";
      sha256 = "1q4nwm9lf4jd90z08s6gz8j1zzrk2jn9vpw49xdb8mwxmhv13xgm";
    };
  }
  {
    goPackagePath = "github.com/prometheus/procfs";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/procfs";
      rev = "e645f4e5aaa8506fc71d6edbc5c4ff02c04c46f2";
      sha256 = "18hwygbawbqilz7h8fl25xpbciwalkslb4igqn4cr9d8sqp7d3np";
    };
  }
  {
    goPackagePath = "github.com/slimsag/godocmd";
    fetch = {
      type = "git";
      url = "https://github.com/slimsag/godocmd";
      rev = "a1005ad29fe3e4831773a8184ee7ebb3a41d1347";
      sha256 = "0vx5j77f02rzr1rrjpjabfj85l72zdpdqc7xv7wrzafm39szfwwn";
    };
  }
  {
    goPackagePath = "github.com/sourcegraph/ctxvfs";
    fetch = {
      type = "git";
      url = "https://github.com/sourcegraph/ctxvfs";
      rev = "8de691b1d0d2eafd764a63aef324fc0a6a8f4da7";
      sha256 = "0xy6y0zb1nji96sfx45i7qxj800ahlkm39pjzh5rp389fmj8ay8x";
    };
  }
  {
    goPackagePath = "github.com/sourcegraph/jsonrpc2";
    fetch = {
      type = "git";
      url = "https://github.com/sourcegraph/jsonrpc2";
      rev = "b02337b177765febba753be4b7d9c26e3a9fd220";
      sha256 = "0f0p68nh68jlr701scyrihisykn0wfjm6f84cnbham3wlfkmqmw2";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "054b33e6527139ad5b1ec2f6232c3b175bd9a30c";
      sha256 = "14rxdrv0yyh1xnblrd943ybj3k836sg4myy3hm4wf64p0c5k92wk";
    };
  }
  {
    goPackagePath = "golang.org/x/tools";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/tools";
      rev = "bce9606b3f617bc6280aab6abbf25962c23f398d";
      sha256 = "19wdbgq56fnw7841h4cplpsy4w756y10xih7ldm3kvwa97p1h7m8";
    };
  }
]
